### ISSUE TITLE
BUG ?

### ISSUE THREAD

**Issue by icyfox168168** [DispatchCode/Machine-Code-Analyzer#1]
MOV       r8, 0x4b4458dd2af77334         OK 10     KO 6 

MOV       r9, 0xfa0b7f3cb79bf9d0 10 6 

MOV       r10, 0xfa0b7f3cb79b92bf 10 6 

MOV       word ptr [rbp+0x284], 0x0000 9 11 

MOV       r15, 0x06bca1af286bca1b 10 6 

MOV       r14, 0x06bca1af286bca1b 10 6

**Comment by DispatchCode** [comment]
Hello, what are the numbers after the instructions?

The x64 code that you have used is just what you can see below?

```
MOV r8, 0x4b4458dd2af77334
MOV r9, 0xfa0b7f3cb79bf9d0
MOV r10, 0xfa0b7f3cb79b92bf 
MOV word ptr [rbp+0x284], 0x0000
MOV r15, 0x06bca1af286bca1b
MOV r14, 0x06bca1af286bca1b
```

I will look at this issue as soon as possible in this days.

Thanks

**Comment by icyfox168168** [comment]
我修改了几个点，不知道是不是完美修复

VZEROUPPER 指令不正确 修改 modrm_2b 77 为 0

    if(instr->vex[0] == 0xC5) {
        #ifdef _ENABLE_VEX_INFO
            instr->_vex.type = instr->vex[0];
            instr->_vex.val5 = instr->vex[1];
        #endif

        mca_decode_modrm(instr, arch, data, modrm_2b, imm_byte_2b);
    }
            case 0x48:
                if(arch == X64)
                    instr->set_prefix |= OP64;
            break;
            case 0x49:  // add
                if (arch == X64)
                    instr->set_prefix |= OP64;
                break;
            case 0x64:
                instr->set_prefix |= FS;
            break;

**Comment by icyfox168168** [comment]
我修改三个地方，不知道有没引入Bug,我仅仅测试x64

我用其他反汇编引擎比较大小，不一样就输出信息，目前还可以

      case z1:
            if(instr->set_prefix & OS)
                return 2;

**Comment by DispatchCode** [comment]
Thanks for your suggestion and for your report.

I have running some tests after applied your hint and seems working. You can find it in the new branch fix_rex_49.
Let me know if the problem is solved.

**Comment by icyfox168168** [comment]
这个指令存在问题，其他我指令测试了，完美

ModRm VZEROUPPER  0 116
Length  VZEROUPPER 3 6

**Comment by DispatchCode** [comment]
Hi, I get this as output:

`Bytes from file: C5 F8 77 CC CC CC CC CC CC CC CC CC CC CC CC CC
RAW bytes (hex): C5 F8 77 CC
Instr. length: 4
Print instruction fields:
        Located Prefixes 0:

        VEX prefix value:
                0xC5 0xF8
        Field 0xF8:
                r: 1
                v: F
                L: 0
                pp: 0

        OP: 0x77
        mod_reg_rm: 0xCC
------------------------------------------------`

I think that the bug is in this lookup table (0x77):

`static size_t modrm_2b[256] = {
        //       00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
        /* 00 */ P1,P1,P1,P1,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        /* 10 */ P7,P7,P7,P2,P2,P2,P6,P2,P1,0, 0, 0, 0, 0, 0, P1,
        /* 20 */ P1,P1,P1,P1,0, 0, 0, 0, P2,P2,P7,P2,P7,P7,P2,P2,
        /* 30 */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        /* 40 */ P1,P1,P1,P1,P1,P1,P1,P1,P1,P1,P1,P1,P1,P1,P1,P1,
        /* 50 */ P2,P7,P4,P4,P2,P2,P2,P2,P7,P7,P7,P6,P7,P7,P7,P7,
        /* 60 */ P2,P2,P2,P2,P2,P2,P2,P2,P2,P2,P2,P2,O66,O66,P2,P2,
        /* 70 */ P7,P1,P1,P1,P2,P2,P2,P1,P1,P1, 0, 0,P5,P5,P6,P6,
        /* 80 */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        /* 90 */ P1,P1,P1,P1,P1,P1,P1,P1,P1,P1,P1,P1,P1,P1,P1,P1,
        /* A0 */ 0, 0, 0, P1,P1,P1, 0, 0, 0, 0, 0,P1,P1,P1,P1,P1,
        /* B0 */ P1,P1,P1,P1,P1,P1,P1,P1,OF3,P1,P1,P1,P4,P4,P1,P1,
        /* C0 */ P1,P1,P7,P1,P2,P2,P2,P1, 0, 0, 0, 0, 0, 0, 0, 0,
        /* D0 */ P5,P2,P2,P2,P2,P2,P8,P2,P2,P2,P2,P2,P2,P2,P2,P2,
        /* E0 */ P2,P2,P2,P2,P2,P2,P8,P2,P2,P2,P2,P2,P2,P2,P2,P2,
        /* F0 */ OF2,P2,P2,P2,P2,P2,P2,P2,P2,P2,P2,P2,P2,P2,P2, 0
};`

as soon as possibile I will take a look into it.

Thanks!
